### ISSUE TITLE
Typescript compiler failed - didn't find ionic-native module

### ISSUE THREAD

**Issue by desicne** [driftyco/ionic-cli#1470]
After starting the tabs project with ionic --v2, the initial serve did not complete. Found error.

`typescript compiler failed:  src/app/app.component.ts(3,27): error TS2307: Cannot find module 'ionic-native'`

The issue is with cordova Status bar added by default. After I remove it from the following file, the tabs template app works.

I ran the following: 
ionic 2.1.0
cordova 6.3.1
node 6.7.0
typescript 2.0.3

**Comment by desicne** [comment]
Ok, so the problem was trivial and it had to do somewhat with my setup. But maybe mark for some installation readme update. 

Even if in package.json I had ionic-native v2.0.3 in deps, only after running `npm install ionic-native --save` it compiled everything correctly. Like I said, the weird thing is that it was installed that way initially.

**Comment by jayakrishnapulipati** [comment]
Thanks It worked out for me :)

**Comment by tohagan** [comment]
If you see this error when upgrading to Ionic 3.x from 2.x don't run `npm install ionic-native --save` as it may install an old version!  Instead, patch your code to use the new `@ionic-native/core`,  `@ionic-native/status-bar` or ``@ionic-native/splash-screen`.  Note that `StatusBar` and `SplashScreen` now require instances (see new documentation).

**Comment by gregv21v** [comment]
To fix the error on my machine, I switched the following:

import { StatusBar, SplashScreen } from 'ionic-native';

to 

import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

Now I get a @ionic-native/splash-screen error.

**Comment by contegiuseppe** [comment]
@tohagan can you explain how to " patch your code to use the new @ionic-native/core, @ionic-native/status-bar or @ionic-native/splash-screen" ? Thank you
