### ISSUE TITLE
ionic start cutePuppyPics --v2 install errors

### ISSUE THREAD

**Issue by hlobil** [driftyco/ionic-cli#647]
no cute puppies :(

[~/Projects]$ ionic start cutePuppyPics --v2

Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/pavelsmacbookpro/local/node/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/npm/lib/config/core.js:2:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

Cannot find module 'config-chain' (CLI v2.0.0-alpha.18)

Your system information:

Cordova CLI: 5.4.0
Ionic CLI Version: 2.0.0-alpha.18
Ionic App Lib Version: 2.0.0-alpha.17
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v5.0.0
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by jbavari** [comment]
@hlobil Sorry you encountered this.

Have you recently updated your node version?

**Comment by maartenhemmes** [comment]
I also encounter the same issue after I upgraded node to v5.0.0

**Comment by laidig** [comment]
I have the same issue with 4.2.2 (installed via nvm) and Ionic CLI 1.7.10

~$ ionic start myapp blank

Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/npm/lib/config/core.js:2:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

Cannot find module 'config-chain' (CLI v1.7.10)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.8.11
Ionic CLI Version: 1.7.10
Ionic App Lib Version: 0.6.5
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v4.2.2

Is there any more info I can provide?

**Comment by maartenhemmes** [comment]
@laidig I'm not sure if this is going to help, but you might want try and update both Ionic and Cordova. My problem got resolved after downgrading node, but I'm running a more recent version of Ionic (1.7.8) and Cordova (5.4.0).

**Comment by laidig** [comment]
I'm running 1.7.10 (semver gets confusing like that), and I upgraded to
cordova-cli 5.4.0 .
Still have the same problem :(

**Comment by tlancina** [comment]
Trying to track this one down, @laidig did this happen only after you had upgraded to 1.7.10?

**Comment by laidig** [comment]
Yes. If it helps i made a big jump, from 1.6.x.

**Comment by tlancina** [comment]
@laidig thanks, what version of npm are you using? Also does `npm cache clean` and a reinstall of ionic fix it for you?

**Comment by laidig** [comment]
That did it for me. Thanks!

**Comment by VERKYSSE** [comment]
J'avais le meme probleme mais j'ai resolu le can't find module 'config-chain'
comment jai procede j'avais la version 5 de node js et jai installe ionic (2) :ionic@alpha .mais j'ai du  revenir  sur la version 4.2.3 de node js pour creer ma premier application avec ionic .

I had the same problem but I can not find resolved the module config- chain '
how i PROCESS I had version 5 node js and I have moved Ionic (2): Ionic @ alpha .but I had to go back on version 4.2.3 node js to create my first application with Ionic .

**Comment by nathanhleung** [comment]
@tlancina I was having the same problem, it worked for me as well.

**Comment by jgw96** [comment]
Hello all, as this seems to be an npm issue and not an ionic issue i will be closing this issue for now. Thanks for using Ionic!
