### ISSUE TITLE
Ionic Serve doesnt work after updated to 2.2.0 followed guide in blog.ionic

### ISSUE THREAD

**Issue by mjakupi** [driftyco/ionic-cli#1970]
TypeError: appScripts.serve is not a function getting this error

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by mjakupi** [comment]
Thanks didnt try that one it fixed my problem :)
