### ISSUE TITLE
Ionic CLI is NOT backwards compatible for me. Ionic 1.7.14 has to be reinstalled after installing 2.0

### ISSUE THREAD

**Issue by shotbyabel** [driftyco/ionic-cli#1019]
It seems that every time I work on an Ionic 2 app and Want to go back and continue working on my ionic 1.7.14 app my Ionic CLI thinks I want to use Ionic 2 and I have to re-install ionic 1.7.14 in order to run simple ionic commands like `ionic build ios` or even `ionic info`

**I get this..** 

    $ ionic info
    WARN: ionic.project has been renamed to ionic.config.json, please rename it.
    Uh oh! Looks like you're missing a module in your gulpfile:
    Cannot find module 'bower'

    Do you need to run `npm install`?

In the past I have switch to Node 4.4.4 and now I need to also re-install ionic 1.7.14 via npm to get my ionic 1 projects to build and run CLI commands.. 

**What can be the issue?**
